#!/bin/bash

#get username
#userName=$(whoami)
#echo "username is: "$userName

#close Slack
killall Slack

#fix helper
#sudo chown -R $userName:staff /Applications/Slack.app


#### remove and reinstall
sudo rm -rf /Applications/Slack.app

#set directories
echo "Setting directories..."
finalURL=$(curl https://slack.com/ssb/download-osx -s -L -I -o /dev/null -w '%{url_effective}')
dmgfile="Slack.dmg"
dir=/tmp/$dmgfile

#download file
echo "Downloading..."
sudo /usr/bin/curl --retry 3 -L "$finalURL" -o $dir

#mount dmg
echo "Mounting dmg..."
/usr/bin/hdiutil attach $dir -nobrowse -quiet

#copy app over
echo "Coping App to Applications folder..."
ditto -rsrc "/Volumes/Slack/Slack.app" "/Applications/Slack.app"

#sleep 3
echo "Sleep 3"
sleep 3

#unmount dmg
echo "Unmounting dmg...."
/usr/bin/hdiutil detach $(/bin/df | /usr/bin/grep "Slack" | awk '{print $1}') -quiet

#delete temp file
echo "Cleaning up..."
sudo rm -Rf $dir



#open Slack
open /Applications/Slack.app

exit 0
